subcategory_weights = {
    # Shirts category
    ("T-Shirts", "Jeans"): 15,
    ("T-Shirts", "Sweatpants"): 18,
    ("T-Shirts", "Shorts"): 12,
    ("T-Shirts", "Dress trousers"): 35,
    ("T-Shirts", "Chinos"): 30,
    ("Button-ups", "Jeans"): 40,
    ("Button-ups", "Sweatpants"): 65,
    ("Button-ups", "Shorts"): 50,
    ("Button-ups", "Dress trousers"): 25,
    ("Button-ups", "Chinos"): 30,
    ("Polo-shirts", "Jeans"): 20,
    ("Polo-shirts", "Sweatpants"): 25,
    ("Polo-shirts", "Shorts"): 15,
    ("Polo-shirts", "Dress trousers"): 40,
    ("Polo-shirts", "Chinos"): 35,

    # Layers category
    ("Sweaters", "Jeans"): 20,
    ("Sweaters", "Sweatpants"): 25,
    ("Sweaters", "Shorts"): 55,
    ("Sweaters", "Dress trousers"): 40,
    ("Sweaters", "Chinos"): 30,
    ("Sweatshirts", "Jeans"): 18,
    ("Sweatshirts", "Sweatpants"): 20,
    ("Sweatshirts", "Shorts"): 50,
    ("Sweatshirts", "Dress trousers"): 40,
    ("Sweatshirts", "Chinos"): 35,
    ("Jackets", "Jeans"): 20,
    ("Jackets", "Sweatpants"): 30,
    ("Jackets", "Shorts"): 60,
    ("Jackets", "Dress trousers"): 35,
    ("Jackets", "Chinos"): 25,
    ("Cover ups", "Jeans"): 35,
    ("Cover ups", "Sweatpants"): 40,
    ("Cover ups", "Shorts"): 50,
    ("Cover ups", "Dress trousers"): 30,
    ("Cover ups", "Chinos"): 45,
    ("Blazers", "Jeans"): 40,
    ("Blazers", "Sweatpants"): 50,
    ("Blazers", "Shorts"): 70,
    ("Blazers", "Dress trousers"): 30,
    ("Blazers", "Chinos"): 25,

    ("Sweaters", "T-Shirts"): 12,
    ("Sweaters", "Button-ups"): 15,
    ("Sweaters", "Polo-shirts"): 10,
    ("Sweatshirts", "T-Shirts"): 10,
    ("Sweatshirts", "Button-ups"): 18,
    ("Sweatshirts", "Polo-shirts"): 12,
    ("Jackets", "T-Shirts"): 8,
    ("Jackets", "Button-ups"): 10,
    ("Jackets", "Polo-shirts"): 9,
    ("Cover ups", "T-Shirts"): 12,
    ("Cover ups", "Button-ups"): 15,
    ("Cover ups", "Polo-shirts"): 13,
    ("Blazers", "T-Shirts"): 20,
    ("Blazers", "Button-ups"): 8,
    ("Blazers", "Polo-shirts"): 15,

    # Pants category
    ("Jeans", "Sneakers"): 10,
    ("Jeans", "Boots"): 15,
    ("Jeans", "Oxfords"): 30,
    ("Jeans", "Loafers"): 20,
    ("Jeans", "Sandals"): 50,
    ("Sweatpants", "Sneakers"): 15,
    ("Sweatpants", "Boots"): 35,
    ("Sweatpants", "Oxfords"): 40,
    ("Sweatpants", "Loafers"): 30,
    ("Sweatpants", "Sandals"): 35,
    ("Shorts", "Sneakers"): 15,
    ("Shorts", "Boots"): 30,
    ("Shorts", "Oxfords"): 45,
    ("Shorts", "Loafers"): 40,
    ("Shorts", "Sandals"): 20,
    ("Dress trousers", "Sneakers"): 45,
    ("Dress trousers", "Boots"): 40,
    ("Dress trousers", "Oxfords"): 20,
    ("Dress trousers", "Loafers"): 10,
    ("Dress trousers", "Sandals"): 60,
    ("Chinos", "Sneakers"): 25,
    ("Chinos", "Boots"): 30,
    ("Chinos", "Oxfords"): 35,
    ("Chinos", "Loafers"): 40,
    ("Chinos", "Sandals"): 50,

    # Shoes category
    ("Sneakers", "Jeans"): 15,
    ("Sneakers", "Sweatpants"): 20,
    ("Sneakers", "Shorts"): 25,
    ("Sneakers", "Dress trousers"): 60,
    ("Sneakers", "Chinos"): 35,
    ("Boots", "Jeans"): 10,
    ("Boots", "Sweatpants"): 30,
    ("Boots", "Shorts"): 45,
    ("Boots", "Dress trousers"): 40,
    ("Boots", "Chinos"): 45,
    ("Oxfords", "Jeans"): 30,
    ("Oxfords", "Sweatpants"): 50,
    ("Oxfords", "Shorts"): 60,
    ("Oxfords", "Dress trousers"): 15,
    ("Oxfords", "Chinos"): 20,
    ("Loafers", "Jeans"): 35,
    ("Loafers", "Sweatpants"): 50,
    ("Loafers", "Shorts"): 55,
    ("Loafers", "Dress trousers"): 25,
    ("Loafers", "Chinos"): 30,
    ("Sandals", "Jeans"): 40,
    ("Sandals", "Sweatpants"): 30,
    ("Sandals", "Shorts"): 15,
    ("Sandals", "Dress trousers"): 65,
    ("Sandals", "Chinos"): 45,

    ("Sneakers", "T-Shirts"): 8,
    ("Sneakers", "Button-ups"): 15,
    ("Sneakers", "Polo-shirts"): 10,
    ("Boots", "T-Shirts"): 12,
    ("Boots", "Button-ups"): 10,
    ("Boots", "Polo-shirts"): 15,
    ("Oxfords", "T-Shirts"): 25,
    ("Oxfords", "Button-ups"): 8,
    ("Oxfords", "Polo-shirts"): 12,
    ("Loafers", "T-Shirts"): 20,
    ("Loafers", "Button-ups"): 12,
    ("Loafers", "Polo-shirts"): 10,
    ("Sandals", "T-Shirts"): 10,
    ("Sandals", "Button-ups"): 30,
    ("Sandals", "Polo-shirts"): 15,

    # Accessories category
    ("Earrings", "Jeans"): 10,
    ("Earrings", "Sweatpants"): 5,
    ("Earrings", "Shorts"): 15,
    ("Earrings", "Dress trousers"): 12,
    ("Earrings", "Chinos"): 20,
    ("Necklaces", "Jeans"): 15,
    ("Necklaces", "Sweatpants"): 10,
    ("Necklaces", "Shorts"): 20,
    ("Necklaces", "Dress trousers"): 12,
    ("Necklaces", "Chinos"): 18,
    ("Rings", "Jeans"): 10,
    ("Rings", "Sweatpants"): 12,
    ("Rings", "Shorts"): 18,
    ("Rings", "Dress trousers"): 15,
    ("Rings", "Chinos"): 22,
    ("Scarves", "Jeans"): 8,
    ("Scarves", "Sweatpants"): 10,
    ("Scarves", "Shorts"): 18,
    ("Scarves", "Dress trousers"): 20,
    ("Scarves", "Chinos"): 25,
    ("Hats", "Jeans"): 15,
    ("Hats", "Sweatpants"): 20,
    ("Hats", "Shorts"): 12,
    ("Hats", "Dress trousers"): 10,
    ("Hats", "Chinos"): 8,
    ("Bags", "Jeans"): 12,
    ("Bags", "Sweatpants"): 15,
    ("Bags", "Shorts"): 20,
    ("Bags", "Dress trousers"): 25,
    ("Bags", "Chinos"): 20,
    ("Sunglasses", "Jeans"): 10,
    ("Sunglasses", "Sweatpants"): 8,
    ("Sunglasses", "Shorts"): 12,
    ("Sunglasses", "Dress trousers"): 20,
    ("Sunglasses", "Chinos"): 15,
    ("Belts", "Jeans"): 10,
    ("Belts", "Sweatpants"): 15,
    ("Belts", "Shorts"): 18,
    ("Belts", "Dress trousers"): 20,
    ("Belts", "Chinos"): 22,
    ("Bracelets", "Jeans"): 8,
    ("Bracelets", "Sweatpants"): 10,
    ("Bracelets", "Shorts"): 18,
    ("Bracelets", "Dress trousers"): 20,
    ("Bracelets", "Chinos"): 25,
    ("Face masks", "Jeans"): 7,
    ("Face masks", "Sweatpants"): 10,
    ("Face masks", "Shorts"): 15,
    ("Face masks", "Dress trousers"): 25,
    ("Face masks", "Chinos"): 22,
    ("Watches", "Jeans"): 12,
    ("Watches", "Sweatpants"): 18,
    ("Watches", "Shorts"): 20,
    ("Watches", "Dress trousers"): 30,
    ("Watches", "Chinos"): 25,
}

